### ISSUE TITLE
Qwest engineering documentation

### ISSUE THREAD

**Issue by atareversei** [basliqlabs/qwest-docs#23]
- [x] #24
- [ ] Update documentation to reflect the newest changes
- [ ] Backend architecture and technologies
- [ ] Frontend architecture and technologies
- [ ] UI/UX fundamentals
