### ISSUE TITLE
List of features for version 1

### ISSUE THREAD

**Issue by atareversei** [basliqlabs/qwest-docs#24]
## User
- [ ] Signup and login
- [ ] Update profile

## Project management (kanban)
- [ ] Workspaces
- [ ] Boards
- [ ] Lists (columns)
- [ ] Milestones
- [ ] Gantt chart

## People
- [ ] Inviting people to workspaces
- [ ] Teams inside workspaces
- [ ] Access permissions

## Tasks
- [ ] Workspace tasks (with no boards)
- [ ] Tasks
- [ ] Personal tasks (with no workspaces or boards)

## Administrative
- [ ] Manage users
- [ ] Manage workspaces
- [ ] Manage boards
- [ ] Manage tasks

## Other
- [ ] Offline support
